Add openssl support
etcdv3/etcd-client pull request #50
Opened 2023-01-06 07:24 UTC by YuJuncen

Hi David, thanks for your awesome library. During using it, we found that the behavior of `rustls` and `openssl` is pretty different, and TiKV uses the `grpcio` gRPC implementation, which wraps `grpc-core` hence uses `BoringSSL` or `openssl` as its transport layer: this made some struggles for users to choose right TLS certificates(some certificates are suitable for `openssl`, some for `rustls`, however now the users can only use the intersection of them). 

So, we have adapted `openssl` via the `hyper-openssl` library, also tried our best to keep the consistency behavior of the `tonic` gRPC implementation.

Generally, we take over the transport layer via the `connect_with_connector` function, however we found that we cannot use custom connector while using `balanced_channel`, so we have manually created a load balancer `OpenSslDiscover`. 

For not changing the old behavior, the openssl support can be enabled via `tls-openssl` or `tls-openssl-vendored`. When either of them enabled, the config `with_openssl_tls` would be enabled, you can then config it via `manually` or provide some cert or keys via some predefined functions.

Perhaps merge this if you think this is helpful. Also, if you have any comments or suggestions about the patch please let me know. =)

2023-01-09 14:59 UTC, davidli2010 commented
Thank you for your great job! I will spend some time to review this PR.

2023-02-07 08:23 UTC, YuJuncen commented
Hi David, during testing the openssl implementation, we found some problems and updated(The diff is https://github.com/pingcap/etcd-client/pull/3), they are:
- If one of etcd server downs, the load balancer would still choose that node, when it cannot be recovered fast, there might be many failed requests. So we made a `Load` implementation which supports giving up retry over some nodes once detect failure over them.
- During initializing the TLS connection, if there are some errors, the buffered service may fully failed. We need to lazily initializing the connection.

I think the latter should be general-proposed optimization and won't bring any regression, but I'm not sure whether the former is suitable for all scenarios. What do you think? Do we need to adding a feature for disabling it?

2023-02-07 15:17 UTC, davidli2010 commented
Sorry for my delay, I will take some time at this weekend.

2023-02-11 09:36 UTC, davidli2010 requested changes
Frankly I'm not good at openssl, it has been many years since my last coding with openssl. In general this PR is not bad, I think it deserves to merge into master branch.

2023-02-11 09:36 UTC, davidli2010 commented on Cargo.toml
> +tls-openssl = ["openssl", "dep:hyper-openssl", "dep:hyper"]
Currently, the actual MSRV of `etcd-client` is 1.56. The `dep:` syntax is only available starting with Rust 1.60. So do not use `dep:` here.

2023-02-11 09:36 UTC, davidli2010 commented on src/lib.rs
> +pub use crate::openssl_tls::OpenSslClientConfig;
The line 70 and 114 can be merged into one line.

2023-02-11 09:36 UTC, davidli2010 commented on src/openssl_tls/transport.rs
> +#![cfg(feature = "tls-openssl")]
There is `#![cfg(feature = "tls-openssl")]` at the top of `openssl_tls/mod.rs`, is this cfg necessary?

2023-02-11 09:40 UTC, davidli2010 commented
> I think the latter should be general-proposed optimization and won't bring any regression, but I'm not sure whether the former is suitable for all scenarios. What do you think? Do we need to adding a feature for disabling it?

I think it's OK as the default behavior. We can add the feature latter if necessary.

2023-02-12 13:00 UTC, YuJuncen commented
Sorry but I just found I cannot push to `pingcap/etcd-client` directly, so when I wanna make any change in this PR I must open a PR in `pingcap/etcd-client` firstly, and I found GitHub doesn't support changing the base branch for a opened PR.😢
 
For making easier addressing the comments, I would close this and reopen a PR based on a branch I own. (I will soon address these comments and provide the new PR.)

2023-02-12 13:33 UTC, YuJuncen commented
Please review https://github.com/etcdv3/etcd-client/pull/53 (based on a branch I own), sorry for that, I will close this for now.

2023-02-12 13:33 UTC, closed without merging