Implement take_prev_kvs for DeleteResponse
etcdv3/etcd-client pull request #68
Opened 2023-11-13 14:32 UTC by tisonkun

Just like `take_prev_key` for `PutResponse`.

I found this helper function help when HACKING https://github.com/GreptimeTeam/greptimedb/pull/2734.

2023-11-15 10:23 UTC, tisonkun commented
cc @davidli2010

2023-11-16 06:56 UTC, tisonkun commented on src/rpc/kv.rs
> +    /// If `prev_kv` is set in the request, take the previous key-value pairs, leaving an empty vector in its place.
```suggestion
    /// If `prev_kvs` is set in the request, take the previous key-value pairs, leaving an empty vector in its place.
```

2023-11-19 06:36 UTC, tisonkun commented
@davidli2010 Do you think this patch in a good direction? Also, I wonder if we have an estimate for a next release so that downstream can upgrade to a version with new patches >_<

2023-11-19 11:36 UTC, davidli2010 commented
> @davidli2010 Do you think this patch in a good direction? Also, I wonder if we have an estimate for a next release so that downstream can upgrade to a version with new patches >_<

This PR is OK, but need to improve the implementation according to my comment.

There is no regular release plan, just release as needed.

2023-11-19 11:59 UTC, tisonkun commented
> need to improve the implementation according to my comment

I don't see extra comments yet.

2023-11-19 12:21 UTC, davidli2010 requested changes

2023-11-19 12:44 UTC, tisonkun commented on src/rpc/kv.rs
> +        self.0.prev_kvs.drain(..).map(KeyValue::new).collect()
Updated.

2023-11-20 01:07 UTC, merged

2023-11-20 02:23 UTC, tisonkun commented
@davidli2010 Thanks for your review. According to release on demand, perhaps I can expect a release in these days?

2023-11-20 13:44 UTC, tisonkun commented
Thank you!