feat: implement namespace APIs
etcdv3/etcd-client pull request #71
Opened 2023-11-23 10:12 UTC by tisonkun

This closes #67.

Still WIP - for preview on the impl direction

2023-11-23 10:12 UTC, tisonkun commented on src/lib.rs
> +fn take_mut<T, F>(mut_ref: &mut T, closure: F)
This is from https://github.com/Sgeo/take_mut to largely simplify code.

2023-11-23 13:21 UTC, tisonkun commented on src/namespace/kv.rs
> +        // TODO (@tisonkun) prefix range_end in options
DeleteOptions make take_mut but the abstraction is strange a bit.

Others are implemented.

2023-11-28 17:14 UTC, davidli2010 commented
I will take a look at this over the weekend.

2023-12-03 00:25 UTC, tisonkun commented
@davidli2010 thank you and as a kindly remind :D

2023-12-03 07:23 UTC, davidli2010 requested changes
I took a quick look at the PR and the namespace APIs were not complicated, but there was too much unnecessary memory allocation. I think we can implement the method of adding and stripping prefix on Vec, while avoiding multiple allocations of memory, and then other code can implement from there:

```rust
trait VecExt {
    fn push_prefix(&mut self, prefix: &[u8]);
    fn strip_prefix(&mut self, prefix: &[u8]);
}

impl VecExt for Vec<u8> {
    fn push_prefix(&mut self, prefix: &[u8]) {
        if prefix.is_empty() {
            return;
        }

        let prefix_len = prefix.len();
        self.reserve(prefix_len);
        unsafe {
            let self_ptr = self.as_mut_ptr();
            std::ptr::copy(self_ptr, self_ptr.add(prefix_len), self.len());
            std::ptr::copy_nonoverlapping(prefix.as_ptr(), self_ptr, prefix_len);
            self.set_len(self.len() + prefix_len);
        }
    }

    fn strip_prefix(&mut self, prefix: &[u8]) {
        if prefix.is_empty() {
            return;
        }

        if self.starts_with(prefix) {
            let prefix_len = prefix.len();
            let new_len = self.len() - prefix_len;
            unsafe {
                let self_ptr = self.as_mut_ptr();
                std::ptr::copy(self_ptr.add(prefix_len), self_ptr, new_len);
                self.set_len(new_len);
            }
        }
    }
}
```

Then we can implement stripping prefix like this:

```rust
impl PutResponse {
    fn strip_prev_kv_prefix(&mut self, prefix: &[u8]) {
        self.prev_kv.as_mut().map(|kv| { kv.key.strip_prefix(prefix);  });
    }
}
```

2023-12-03 07:23 UTC, davidli2010 commented on src/namespace/mod.rs
> +    let _ = key.splice(..0, pfx.to_vec()).collect::<Vec<_>>();
this line has 2 unnecessary memory allocation

2023-12-03 07:23 UTC, davidli2010 commented on src/namespace/kv.rs
> +        key.split_off(self.pfx.len())
`split_off` has memory allocation that is not necessary for stripping prefix key.

2023-12-04 06:53 UTC, tisonkun commented
@davidli2010 Thanks for your advice! I add the helpers and use them.

Although, I don't extend `strip_prev_kv_prefix` to existing requests but keep using the `take_mut` flavor.

2023-12-09 01:34 UTC, davidli2010 commented
`take_mut` takes the key and write back after modification. IMO, it's unnecessary.

2023-12-09 01:44 UTC, tisonkun commented
```
impl PutResponse {
    fn strip_prev_kv_prefix(&mut self, prefix: &[u8]) {
        self.prev_kv.as_mut().map(|kv| { kv.key.strip_prefix(prefix);  });
    }
}
```

This way is too intrusive and we may have a strange dependency graph for `strip_prefix_xxx_response`.

> take_mut takes the key and write back after modification. IMO, it's unnecessary.

You may try to refactor the code as you wish and see. I don't have a better idea to do now 📦 

And IIUC the current `take_mut` way doesn't introduce heavy operation.

2023-12-10 04:56 UTC, davidli2010 commented
I refactored the code, you can see it in https://github.com/etcdv3/etcd-client/tree/namespace.

2023-12-10 05:00 UTC, tisonkun commented
@davidli2010 your modification looks good, although I may treat them as personal preference differences.

Thanks for your review and refactor! Please go ahead directly updating this PR or use your branch instead :D

2023-12-10 05:06 UTC, davidli2010 commented
I refactored the code, you can see it in https://github.com/etcdv3/etcd-client/tree/namespace.

> @davidli2010 your modification looks good, although I may treat them as personal preference differences.
> 
> Thanks for your review and refactor! Please go ahead directly updating this PR or use your branch instead :D

I pushed the refactored code to this PR. Can you add some basic test cases and example for the namespace APIs?

2023-12-10 05:07 UTC, davidli2010 commented
> @davidli2010 your modification looks good, although I may treat them as personal preference differences.
> 
> Thanks for your review and refactor! Please go ahead directly updating this PR or use your branch instead :D

I pushed the refactored code to this PR. Can you add some basic test cases and example for the namespace APIs?

2023-12-11 16:24 UTC, tisonkun commented
Thank you! Upstream doesn't have test coverage IIRC. But I can prepare some.

I wonder if we have an integration tests framework already, or shall I write one.

2023-12-15 09:03 UTC, davidli2010 commented
You can see test cases of client in https://github.com/etcdv3/etcd-client/blob/f5d427b0e0653fac0a8a3dd5d3d6fafd59a3d366/src/client.rs#L832

I think you can add test cases of namespace APIs in `src/namespace/mod.rs` or `tests/namespace.rs`.

2023-12-15 11:44 UTC, davidli2010 commented
I have splitted test cases to `tests` directory, please see https://github.com/etcdv3/etcd-client/pull/72. You can add namespace test cases in `tests/namespace.rs`, use `testing::get_client` to get client.

2023-12-27 05:06 UTC, tisonkun commented
@davidli2010 Updated.

The upstream contains a test for putget and for watch. We may support watch later.

2024-01-01 03:20 UTC, davidli2010 requested changes

2024-01-01 03:21 UTC, davidli2010 approved these changes

2024-01-01 03:21 UTC, merged